# Generated by Django 3.0.1 on 2020-01-22 22:59

import datetime
import django.core.files.storage
from django.db import migrations, models
import main.formatChecker
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste', models.TextField()),
                ('unique_id_paste', models.CharField(default=main.utils.generate_unique_id_field, max_length=29, verbose_name='unique_id')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='File_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', main.formatChecker.ContentTypeRestrictedFileField(help_text=' @Upload .txt and .html file of 2MB or Less.', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\PiusLucky-CodeWick\\Desktop\\Portfolio - Coding + Design\\Coding\\Img_Base64 Converter\\img_base64_project\\file/'), upload_to='')),
                ('unique_id', models.CharField(default=main.utils.generate_unique_id_file, max_length=20, verbose_name='unique_id')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Image_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', main.formatChecker.ContentTypeRestrictedFileField(help_text=' @Upload image(PNG, Jpeg and GIF only) with size of 1MB or less', max_length=1000, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Link_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='https://www.google.com/example.jpg', max_length=2000)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('unique_id', models.CharField(default=main.utils.generate_unique_id, max_length=18, verbose_name='unique_id')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Link_Model_Decode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='<small><div align="left" >\t \t<b><span style="color:#57b894">INFO:</span>&nbsp;https://www.google.com/example.txt or http://www.abc.com/example.html</b></span></div></small>', max_length=2000)),
                ('unique_id_link', models.CharField(default=main.utils.generate_unique_id_link, max_length=28, verbose_name='unique_id')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Update_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_update', models.TextField(max_length=99999, verbose_name='topUpdate')),
                ('quote', models.TextField(max_length=10000, verbose_name='Quote')),
                ('bottom_update', models.TextField(max_length=999999999, verbose_name='bottomUpdate')),
                ('added_feature', models.TextField(max_length=9999999, verbose_name='Features')),
                ('version_of_update', models.CharField(max_length=9999999, verbose_name='version_of_update')),
                ('contributor', models.TextField(default='PIUS LUCKY', max_length=99999999, verbose_name='contributors')),
                ('authenticate', models.CharField(max_length=10, verbose_name='authenticate')),
                ('update_id', models.CharField(default=main.utils.update_unique_id, max_length=17, verbose_name='update_id')),
                ('updated', models.DateTimeField(default=datetime.datetime(2020, 1, 22, 14, 59, 13, 165321))),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
