# Generated by Django 3.0.1 on 2020-01-23 21:36

import datetime
from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200123_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_model',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='link_model',
            name='unique_id_link',
            field=models.CharField(default=main.utils.generate_unique_id_link, max_length=28, verbose_name='unique_id'),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 22, 36, 23, 49410)),
        ),
    ]
