# Generated by Django 3.0.1 on 2020-01-25 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200125_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq_model',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveField(
            model_name='faq_model',
            name='created',
        ),
        migrations.AddField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 11, 5, 42, 635831)),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q1',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question One'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q10',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Ten'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q2',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Two'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q3',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Three'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q4',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Four'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q5',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Five'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q6',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Six'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q7',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Seven'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q8',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Eight'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='Q9',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Question Nine'),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 11, 5, 42, 635831)),
        ),
    ]
