# Generated by Django 3.0.1 on 2020-01-25 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200125_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 17, 16, 13, 46193)),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 17, 16, 13, 46193)),
        ),
    ]
