# Generated by Django 3.0.1 on 2020-01-26 22:19

import datetime
from django.db import migrations, models
import django.utils.timezone
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200126_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_me_model',
            name='ticket_id',
            field=models.CharField(default=main.utils.ticket_id, max_length=100000, verbose_name='Ticket_ID'),
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100000, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='query',
            field=models.TextField(default=django.utils.timezone.now, max_length=100000, verbose_name='Query'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='seven_digit_auth_code',
            field=models.CharField(default=main.utils.auth_code, max_length=40, verbose_name='Auth_code'),
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='seven_digit_auth_code_enter',
            field=models.CharField(max_length=40, verbose_name='Auth_code_enter'),
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 23, 19, 7, 252890)),
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='whatsapp_contact',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Whatsapp contact'),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 23, 19, 7, 237260)),
        ),
        migrations.AlterField(
            model_name='my_contact_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 23, 19, 7, 237260)),
        ),
        migrations.AlterField(
            model_name='resubmit_ticket_model',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 23, 19, 7, 252890)),
        ),
        migrations.AlterField(
            model_name='resubmit_ticket_model',
            name='seven_digit_auth_code',
            field=models.CharField(default=main.utils.auth_code, max_length=30, verbose_name='Auth_code'),
        ),
        migrations.AlterField(
            model_name='resubmit_ticket_model',
            name='seven_digit_auth_code_enter',
            field=models.CharField(max_length=30, verbose_name='Auth_code_enter'),
        ),
        migrations.AlterField(
            model_name='resubmit_ticket_model',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Ticket_ID'),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 23, 19, 7, 237260)),
        ),
    ]
