# Generated by Django 3.0.1 on 2020-01-27 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200126_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resubmit_Ticket_Model',
        ),
        migrations.AlterField(
            model_name='contact_me_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 22, 16, 42, 17603)),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 22, 16, 42, 17603)),
        ),
        migrations.AlterField(
            model_name='my_contact_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 22, 16, 42, 17603)),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 22, 16, 42, 17603)),
        ),
    ]
