# Generated by Django 3.0.1 on 2020-02-20 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200127_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 13, 41, 0, 148822)),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 13, 41, 0, 133198)),
        ),
        migrations.AlterField(
            model_name='my_contact_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 13, 41, 0, 148822)),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 13, 41, 0, 133198)),
        ),
    ]
