# Generated by Django 3.0.1 on 2020-02-25 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200224_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 41, 33, 685846)),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 41, 33, 677848)),
        ),
        migrations.AlterField(
            model_name='my_contact_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 41, 33, 682847)),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 41, 33, 675846)),
        ),
    ]
