# Generated by Django 3.0.1 on 2020-02-25 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200225_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 58, 48, 402725)),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 58, 48, 398725)),
        ),
        migrations.AlterField(
            model_name='my_contact_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 58, 48, 400725)),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 5, 58, 48, 395725)),
        ),
    ]
