# Generated by Django 3.0.1 on 2020-02-25 08:01

import datetime
from django.db import migrations, models
import main.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200225_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 9, 1, 15, 863889)),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 9, 1, 15, 857890)),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='image',
            field=main.formatChecker.ContentTypeRestrictedFileField(help_text=' @Upload image(PNG, Jpeg and GIF only) with size of 1MB or less', max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='my_contact_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 9, 1, 15, 859890)),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 9, 1, 15, 853890)),
        ),
    ]
