# Generated by Django 3.0.1 on 2020-02-26 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200225_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 17, 15, 1, 221293)),
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 17, 15, 1, 213289)),
        ),
        migrations.AlterField(
            model_name='field_model',
            name='paste',
            field=models.TextField(help_text='Paste in large chunk of your Base64 string here!'),
        ),
        migrations.AlterField(
            model_name='link_model',
            name='url',
            field=models.URLField(help_text='Input link of image with 1MB or below in size.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='my_contact_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 17, 15, 1, 217289)),
        ),
        migrations.AlterField(
            model_name='update_model',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 17, 15, 1, 209290)),
        ),
    ]
